### ISSUE TITLE
DB 설계

### ISSUE THREAD

**Issue by heumsi** [Capstone-Design1/sogang-space#1]
크게, 테이블 필드를 다음과 같이 나눈다.
**(위치) (시설) (환경) (평가)**

- **(위치)**
건물 / 층 / 강의실이름
_e.g.,  J / 3 / J319_

- **(시설)**
시간표 / 강의실 사진 / 평면도 / 면적 / 사용가능인원 / 책상 수 / 시설 종류 (에어컨, 스피커 등) / 활용방법
_e.g., 이하 별도 기재 (1) / J319.jpg / 500 / 30 / 30 / 이하 별도 기재 (2) / 이하 별도 기재 (3)_
_i.e.,_
1) 현재 시간이 4시이고, 해당 강의실이 4시 30분부터 수업이 진행될 예정일 경우, 쉬는 시간을 제외한 4시 15분까지 사용가능이라는 정보를 제공하려함.

2) 시설 종류는 에어컨, 프로젝터, 스크린, 스피커, 화이트보드, 엘리베이터 접근성, 분리형 책상, 일체형 책상, 와이파이 column에 대하여, 유/무 방식으로 입력 받음.

3) 활용 방법은 활용방법 (1)과 활용방법 (2) column으로 구성하여, 공부, 발표, 수업 등과 같은 이용 방법을 하나씩 입력 받음.

- **(환경)**
시간 / 온도 / 습도 / 이산화탄소 / 미세먼지
_e.g., 2018-05-10 : 09:14:00 / 24.5 / 34 / 870 / 20_

- **(평가)**
사람 수 / 환경점수(5점 만점) / 불쾌지수(Trello 에서 모델 확인)
_e.g., 3 / 3.5 / 60_

**Comment by heumsi** [comment]
@mhnam (시설) ex 작성 부탁드려요.

**Comment by taeseunglee** [comment]
* (시설 table) FACILITY
field  : 강의실 이름(PK) | 건물  | 층 | 평면도      | 면적   | 사용 가능 인원  | 책상 수  | 시설 종류            |
ex     :        J319           |  J      | 3  | ..?           | 50.2 | 30                   | 30       |  [0, 4]  |
type :        vc [16]        |  v[8] | i    | ppp.jpg | do    | int                   | int        |  int[]  |

* (시간표 table) TIMETABLE
field :  과목 번호(PK) | 강의실 이름(FK) | 시작 시각 | 종료 시각
type :   vc[16]           | vc[16]              | time       | timestamp

* (환경정보 table) ENVIRONMENT
field :  방이름 / 시간  / 온도       / 습도      / 이산화탄소 / 미세먼지
type : time / double / double /  int            /   int

* (평가 table) ESTIMATION
field : 방이름 / 시간 / 환경점수 / 불쾌지수
type : time / real / integer

**Comment by taeseunglee** [comment]
시설 table 생성 query
``` mysql
CREATE TABLE facility (
    name            text primary key,
    building        text,
    floor           integer,
    floor_plan      text,
    area            real,
    accomodation    integer,
    num_desk        integer,
    facilities      integer[]
);
```
시간표 table 생성 query : 
```mysql
CREATE TYPE day_of_week AS ENUM ('mon', 'tue', 'wen', 'thr', 'fri', 'sat', 'sun');

CREATE TYPE time_period AS
(
    day   day_of_week,
    start date,
    end   date
);

CREATE TABLE TIMETABLE (
    subject_num   varchar[16],
    room_name     varchar[16] references facility(name),
    time    interval
);
```

환경정보 table query
```mysql
CREATE TABLE ENVIRONMENT (
    room_name     text references facility(name),
    intime   timestamp,
    temp  real,
    humidity  real,
    co2     integer,
    dust    integer    
);
```

평가 table
```mysql
CREATE TABLE ESTIMATION (
    room_name     text references facility(name),
    time timestamp,
    score  real,
    discomfort integer
);
```

**Comment by heumsi** [comment]
환경정보, 평가 table

에 name 필드가 없네요. name field 로 join 시켜서 찾아야 할 듯 한데요.

**Comment by taeseunglee** [comment]
시간표 table을 제외하고 모두 생성하였습니다.

user : 'admin'
host: '127.0.0.1'
database : 'bangdb'
password : '123123'
port: '5432'

**Comment by mhnam** [comment]
@heumsi 시설 테이블 관련 요청사항 입력하였습니다.

**Comment by stonehye** [comment]
http://victorydntmd.tistory.com/12

개설교과목정보에서 엑셀파일 다운로드 후 원하는 정보만 보고싶을 때 도움될 것 같습니다. 정확히는 모르겠지만 Ruby인거 같습니다(...)

**Comment by stonehye** [comment]
[php] csv 파일에 있는 data를 postgresql 테이블에 insert 하기
http://ujink.tistory.com/4

**Comment by taeseunglee** [comment]
Environment table
<img width="507" alt="2018-06-05 7 27 04" src="https://user-images.githubusercontent.com/9005291/40970759-8524dda2-68f6-11e8-93ee-4b78f8d66d15.png">

**Comment by taeseunglee** [comment]
POST
/api/room/:roomName/temp/:temp/humidity/:humidity/co2/:co2/dust/:dust

ex.
[ip]:8000/api/room/K501/temp/24.5/humidity/30/co2/856/dust/15

**Comment by taeseunglee** [comment]
DB에서 값 확인 하는 방법 
<img width="610" alt="2018-06-05 10 01 22" src="https://user-images.githubusercontent.com/9005291/40977526-26c71d4a-690c-11e8-9739-cd7217597ac6.png">

확인하는 API : http://ec2-13-209-35-182.ap-northeast-2.compute.amazonaws.com:8000/api/room/:roomName

Json 보기 쉽게 하는 확장 프로그램: JsonView Chrome Extension
