### ISSUE TITLE
RESTful API 설계

### ISSUE THREAD

**Issue by taeseunglee** [Capstone-Design1/sogang-space#2]

**Comment by heumsi** [comment]
다음 request 들 어디로 보내면 될지 알려주세요.

**1. 건물 정보에 대한 request**
`{ name : (value) }`
ex.
`{name : 'J'}`

request 에 대한 원하는 response
ex.
```
{
    evaluation : 4.3,
    temperature : 25.4,
    humidity : 50,
    co2 : 540,
    dust : 10
}
```

**2. 건물 내 층 정보에 대한 request**
`{ name : (value), floor : (value) }`
ex.
`{name : 'J', floor : '3'}`

request 에 대한 원하는 response
ex.
```
{
    evaluation : 4.3,
    temperature : 25.4,
    humidity : 50,
    co2 : 540,
    dust : 10
}
```

**3. 강의실에 대한 request**
`{ name : (value) }`
ex. 
`{name : 'J319'}`

request 에 대한 원하는 response
ex.
```
{
    evaluation : 4.3,
    temperature : 25.4,
    humidity : 50,
    co2 : 540,
    dust : 10,
    presence : True
}
```
